// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elmczrfjjgbvqpohmlif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsbWN6cmZqamdidnFwb2htbGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0MjM3OTEsImV4cCI6MjA0OTk5OTc5MX0.b12GueaIsB4JT9948tksUcQkEJFovmYnytj-tr7w6AY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);